# Generated by Django 5.2.11 on 2026-02-10 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_gamesession_remaining_reroles"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="nickname",
            field=models.CharField(
                default="익명투자자", max_length=20, verbose_name="닉네임"
            ),
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="플레이어",
            ),
        ),
    ]
